import type { IconifyIcon } from '@iconify/types';
import chevronDown from '@iconify/icons-tabler/chevron-down';
import chevronUp from '@iconify/icons-tabler/chevron-up';
import heart from '@iconify/icons-tabler/heart';
import heartFilled from '@iconify/icons-tabler/heart-filled';
import play from '@iconify/icons-tabler/play';
import pause from '@iconify/icons-tabler/pause';
import list from '@iconify/icons-tabler/list';
import search from '@iconify/icons-tabler/search';
import plus from '@iconify/icons-tabler/plus';
import minus from '@iconify/icons-tabler/minus';
import grid from '@iconify/icons-tabler/grid';
import music from '@iconify/icons-tabler/music';
import alertTriangle from '@iconify/icons-tabler/alert-triangle';
import messageCircle from '@iconify/icons-tabler/message-circle';
import square from '@iconify/icons-tabler/square';
import check from '@iconify/icons-tabler/circle-check';
import bot from '@iconify/icons-tabler/message-dots';
import volume2 from '@iconify/icons-tabler/volume-2';
import volume1 from '@iconify/icons-tabler/volume';
import volumeX from '@iconify/icons-tabler/volume-off';
import volume from '@iconify/icons-tabler/volume-off';
import repeat from '@iconify/icons-tabler/repeat';
import repeatOnce from '@iconify/icons-tabler/repeat-once';
import shuffle from '@iconify/icons-tabler/arrows-shuffle';
import skipBack from '@iconify/icons-tabler/player-skip-back';
import skipForward from '@iconify/icons-tabler/player-skip-forward';
import trash2 from '@iconify/icons-tabler/trash';
import x from '@iconify/icons-tabler/x';
import chevronUpDown from '@iconify/icons-tabler/switch-vertical';
import arrowUp from '@iconify/icons-tabler/arrow-up';
import maximize2 from '@iconify/icons-tabler/arrows-maximize';
import scan from '@iconify/icons-tabler/scan';
import chevronLeft from '@iconify/icons-tabler/chevron-left';
import qrCode from '@iconify/icons-tabler/qrcode';
import smartphone from '@iconify/icons-tabler/device-mobile';
import user from '@iconify/icons-tabler/user';
import image from '@iconify/icons-tabler/photo';
import thumbsUp from '@iconify/icons-tabler/thumb-up';
import logOut from '@iconify/icons-tabler/logout';
import gift from '@iconify/icons-tabler/gift';
import home from '@iconify/icons-tabler/home';
import chevronRight from '@iconify/icons-tabler/chevron-right';
import refreshCw from '@iconify/icons-tabler/refresh';
import sliders from '@iconify/icons-tabler/adjustments';
import compass from '@iconify/icons-tabler/compass';
import clock from '@iconify/icons-tabler/clock';
import speedometer from '@iconify/icons-tabler/gauge';
import pulse from '@iconify/icons-tabler/heartbeat';
import cloud from '@iconify/icons-tabler/cloud';
import settings from '@iconify/icons-tabler/settings';
import star from '@iconify/icons-tabler/star';
import shield from '@iconify/icons-tabler/shield';
import info from '@iconify/icons-tabler/info-circle';
import externalLink from '@iconify/icons-tabler/external-link';
import palette from '@iconify/icons-tabler/palette';
import playerPlay from '@iconify/icons-tabler/player-play';
import keyboard from '@iconify/icons-tabler/keyboard';
import deviceSpeaker from '@iconify/icons-tabler/device-speaker';
import flask from '@iconify/icons-tabler/flask';
import arrowNarrowUp from '@iconify/icons-tabler/arrow-narrow-up';
import arrowNarrowDown from '@iconify/icons-tabler/arrow-narrow-down';
import currentLocation from '@iconify/icons-tabler/current-location';

export const iconChevronDown = chevronDown as IconifyIcon;
export const iconChevronUp = chevronUp as IconifyIcon;
export const iconHeart = heart as IconifyIcon;
export const iconHeartFilled = heartFilled as IconifyIcon;
export const iconPlay = play as IconifyIcon;
export const iconPause = pause as IconifyIcon;
export const iconList = list as IconifyIcon;
export const iconSearch = search as IconifyIcon;
export const iconPlus = plus as IconifyIcon;
export const iconMinus = minus as IconifyIcon;
export const iconGrid = grid as IconifyIcon;
export const iconMusic = music as IconifyIcon;
export const iconTriangleAlert = alertTriangle as IconifyIcon;
export const iconMessageCircle = messageCircle as IconifyIcon;
export const iconSquare = square as IconifyIcon;
export const iconCheck = check as IconifyIcon;
export const iconBotMessageSquare = bot as IconifyIcon;
export const iconVolume2 = volume2 as IconifyIcon;
export const iconVolume1 = volume1 as IconifyIcon;
export const iconVolumeX = volumeX as IconifyIcon;
export const iconVolumeOff = volume as IconifyIcon;
export const iconRepeat = repeat as IconifyIcon;
export const iconShuffle = shuffle as IconifyIcon;
export const iconListRestart = repeatOnce as IconifyIcon;
export const iconSkipBack = skipBack as IconifyIcon;
export const iconSkipForward = skipForward as IconifyIcon;
export const iconStepBack = skipBack as IconifyIcon;
export const iconStepForward = skipForward as IconifyIcon;
export const iconTrash = trash2 as IconifyIcon;
export const iconX = x as IconifyIcon;
export const iconChevronUpDown = chevronUpDown as IconifyIcon;
export const iconArrowUp = arrowUp as IconifyIcon;
export const iconFullscreen = maximize2 as IconifyIcon;
export const iconScan = scan as IconifyIcon;
export const iconChevronLeft = chevronLeft as IconifyIcon;
export const iconQrCode = qrCode as IconifyIcon;
export const iconSmartphone = smartphone as IconifyIcon;
export const iconUser = user as IconifyIcon;
export const iconImage = image as IconifyIcon;
export const iconThumbsUp = thumbsUp as IconifyIcon;
export const iconLogOut = logOut as IconifyIcon;
export const iconGift = gift as IconifyIcon;
export const iconHome = home as IconifyIcon;
export const iconChevronRight = chevronRight as IconifyIcon;
export const iconRefreshCw = refreshCw as IconifyIcon;
export const iconSparkles = star as IconifyIcon;
export const iconCompass = compass as IconifyIcon;
export const iconClock = clock as IconifyIcon;
export const iconSpeedometer = speedometer as IconifyIcon;
export const iconPulse = pulse as IconifyIcon;
export const iconCloud = cloud as IconifyIcon;
export const iconSettings = settings as IconifyIcon;
export const iconSlidersHorizontal = sliders as IconifyIcon;
export const iconStar = star as IconifyIcon;
export const iconShield = shield as IconifyIcon;
export const iconInfo = info as IconifyIcon;
export const iconExternalLink = externalLink as IconifyIcon;
export const iconPalette = palette as IconifyIcon;
export const iconPlayerPlay = playerPlay as IconifyIcon;
export const iconKeyboard = keyboard as IconifyIcon;
export const iconDeviceSpeaker = deviceSpeaker as IconifyIcon;
export const iconFlask = flask as IconifyIcon;
export const iconSortUp = arrowNarrowUp as IconifyIcon;
export const iconSortDown = arrowNarrowDown as IconifyIcon;
export const iconCurrentLocation = currentLocation as IconifyIcon;
